name="Daniela Riaño"
print(name)
print("Hola Mundo")
num_1=7000000
num_2= 50
print(num_1*num_2)
jugador=input("Dame tu nombre")
juego=input("Dime el juego que quieres")
ciudad=input("De que ciudad eres")
print ("Hola",jugador)
print("Hola",jugador,"Bienvenid@s") 
print("Hola", jugador,"Bienvenid@s","tu", juego, "esta listo")
print(jugador,"Te conectas desde la ciuedad de",ciudad)
edad=int(input("Dame tu edad"))
print(jugador,"Tu edad es",edad,"años")
if edad>=18:
    print("Puedes jugar")
else:
    print("No puedes jugar")
if ciudad=="bogota":
    print("vives en la mejor ciudad del mundo")
else:
    print("no vives en la mejor ciudad de mundo")
